# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
zinit light paulirish/git-open


# Keybind
bindkey -e
bindkey "^p" history-search-backward
bindkey "^n" history-search-forward
bindkey '^H' backward-kill-word
bindkey '^[[3;5~' kill-word
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[3~" delete-char

# Load completions
autoload -U compinit && compinit

# AWS completions
source /usr/bin/aws_zsh_completer.sh

# AWS config
export AWS_CONFIG_FILE=.aws/config
export AWS_SHARED_CREDENTIALS_FILE=.aws/credentials

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Env Variable
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"
export LS_COLORS="$(dircolors -b)"
export PATH="/home/cilgin/.go/bin:$PATH"

# Aliases
alias grep='grep --color=auto'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias boot-windows='sudo grub-reboot 2 && reboot'
alias k="kubectl"
alias open="xdg-open"
alias :q='exit'
alias n="nvim"
alias tf="terraform"
# alias tf="tofu"

# Remove this lines if you don't use eza or exa 
alias ls='eza'
alias la='eza --long --header --icons --git --hyperlink --all'
alias lsd='eza --long --header --icons --git --hyperlink --all --total-size'

# Completion Styling
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Shell integration
eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"
eval "$(dlv completion zsh)"


# Yazi Shell Wrapper
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

eval "$(starship init zsh)"
